create or replace table `gaia_nyc_taxi_trips_ds.taxi_trips` partition by PartitionDate as 
select
'yellow' as TaxiCompany,
vendor_id as Vendor_Id,
pickup_datetime as Pickup_DateTime,
dropoff_datetime as Dropoff_DateTime,
store_and_fwd_flag as Store_And_Forward,
Rate_Code as Rate_Code_Id,
pickup_location_id as PULocationID,
dropoff_location_id as DOLocationID,
Passenger_Count,
trip_distance as Trip_Distance,
fare_amount as Fare_Amount,
imp_surcharge as Surcharge,
mta_tax as MTA_Tax,
tip_amount as Tip_Amount,
tolls_amount as Tolls_Amount,
cast(null as numeric) as Improvement_Surcharge,
total_amount as Total_Amount,
payment_type as Payment_Type_Id,
cast(null as numeric) as Congestion_Surcharge,
cast(null as string) as Trip_Type,   
cast(null as numeric) as Ehail_Fee,   
date(pickup_datetime) as PartitionDate,
cast(null as numeric) as distance_between_service,
cast(null as integer) as time_between_service
from `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2020`
union all
select
'green' as TaxiCompany,
vendor_id as Vendor_Id,
pickup_datetime as Pickup_DateTime,
dropoff_datetime as Dropoff_DateTime,
store_and_fwd_flag as Store_And_Forward,
Rate_Code as Rate_Code_Id,
pickup_location_id as PULocationID,
dropoff_location_id as DOLocationID,
Passenger_Count,
trip_distance as Trip_Distance,
fare_amount as Fare_Amount,
imp_surcharge as Surcharge,
mta_tax as MTA_Tax,
tip_amount as Tip_Amount,
tolls_amount as Tolls_Amount,
cast(null as numeric) as Improvement_Surcharge,
total_amount as Total_Amount,
payment_type as Payment_Type_Id,
cast(null as numeric) as Congestion_Surcharge,
trip_type as Trip_Type, 
cast(Ehail_Fee as numeric) as Ehail_Fee,
date(pickup_datetime) as PartitionDate,
distance_between_service,
time_between_service
from `bigquery-public-data.new_york_taxi_trips.tlc_green_trips_2020`
union all
select
'yellow' as TaxiCompany,
vendor_id as Vendor_Id,
pickup_datetime as Pickup_DateTime,
dropoff_datetime as Dropoff_DateTime,
store_and_fwd_flag as Store_And_Forward,
Rate_Code as Rate_Code_Id,
pickup_location_id as PULocationID,
dropoff_location_id as DOLocationID,
Passenger_Count,
trip_distance as Trip_Distance,
fare_amount as Fare_Amount,
imp_surcharge as Surcharge,
mta_tax as MTA_Tax,
tip_amount as Tip_Amount,
tolls_amount as Tolls_Amount,
cast(null as numeric) as Improvement_Surcharge,
total_amount as Total_Amount,
payment_type as Payment_Type_Id,
cast(null as numeric) as Congestion_Surcharge,
cast(null as string) as Trip_Type,   
cast(null as numeric) as Ehail_Fee,   
date(pickup_datetime) as PartitionDate,
cast(null as numeric) as distance_between_service,
cast(null as integer) as time_between_service
from `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2019`
union all
select
'green' as TaxiCompany,
vendor_id as Vendor_Id,
pickup_datetime as Pickup_DateTime,
dropoff_datetime as Dropoff_DateTime,
store_and_fwd_flag as Store_And_Forward,
Rate_Code as Rate_Code_Id,
pickup_location_id as PULocationID,
dropoff_location_id as DOLocationID,
Passenger_Count,
trip_distance as Trip_Distance,
fare_amount as Fare_Amount,
imp_surcharge as Surcharge,
mta_tax as MTA_Tax,
tip_amount as Tip_Amount,
tolls_amount as Tolls_Amount,
cast(null as numeric) as Improvement_Surcharge,
total_amount as Total_Amount,
payment_type as Payment_Type_Id,
cast(null as numeric) as Congestion_Surcharge,
trip_type as Trip_Type, 
cast(Ehail_Fee as numeric) as Ehail_Fee,
date(pickup_datetime) as PartitionDate,
distance_between_service,
time_between_service
from `bigquery-public-data.new_york_taxi_trips.tlc_green_trips_2019`
union all
select
'yellow' as TaxiCompany,
vendor_id as Vendor_Id,
pickup_datetime as Pickup_DateTime,
dropoff_datetime as Dropoff_DateTime,
store_and_fwd_flag as Store_And_Forward,
Rate_Code as Rate_Code_Id,
pickup_location_id as PULocationID,
dropoff_location_id as DOLocationID,
Passenger_Count,
trip_distance as Trip_Distance,
fare_amount as Fare_Amount,
imp_surcharge as Surcharge,
mta_tax as MTA_Tax,
tip_amount as Tip_Amount,
tolls_amount as Tolls_Amount,
cast(null as numeric) as Improvement_Surcharge,
total_amount as Total_Amount,
payment_type as Payment_Type_Id,
cast(null as numeric) as Congestion_Surcharge,
cast(null as string) as Trip_Type,   
cast(null as numeric) as Ehail_Fee,   
date(pickup_datetime) as PartitionDate,
cast(null as numeric) as distance_between_service,
cast(null as integer) as time_between_service
from `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2018`
union all
select
'green' as TaxiCompany,
vendor_id as Vendor_Id,
pickup_datetime as Pickup_DateTime,
dropoff_datetime as Dropoff_DateTime,
store_and_fwd_flag as Store_And_Forward,
Rate_Code as Rate_Code_Id,
pickup_location_id as PULocationID,
dropoff_location_id as DOLocationID,
Passenger_Count,
trip_distance as Trip_Distance,
fare_amount as Fare_Amount,
imp_surcharge as Surcharge,
mta_tax as MTA_Tax,
tip_amount as Tip_Amount,
tolls_amount as Tolls_Amount,
cast(null as numeric) as Improvement_Surcharge,
total_amount as Total_Amount,
payment_type as Payment_Type_Id,
cast(null as numeric) as Congestion_Surcharge,
trip_type as Trip_Type, 
cast(Ehail_Fee as numeric) as Ehail_Fee,
date(pickup_datetime) as PartitionDate,
distance_between_service,
time_between_service
from `bigquery-public-data.new_york_taxi_trips.tlc_green_trips_2018`
union all
select
'yellow' as TaxiCompany,
vendor_id as Vendor_Id,
pickup_datetime as Pickup_DateTime,
dropoff_datetime as Dropoff_DateTime,
store_and_fwd_flag as Store_And_Forward,
Rate_Code as Rate_Code_Id,
pickup_location_id as PULocationID,
dropoff_location_id as DOLocationID,
Passenger_Count,
trip_distance as Trip_Distance,
fare_amount as Fare_Amount,
imp_surcharge as Surcharge,
mta_tax as MTA_Tax,
tip_amount as Tip_Amount,
tolls_amount as Tolls_Amount,
cast(null as numeric) as Improvement_Surcharge,
total_amount as Total_Amount,
payment_type as Payment_Type_Id,
cast(null as numeric) as Congestion_Surcharge,
cast(null as string) as Trip_Type,   
cast(null as numeric) as Ehail_Fee,   
date(pickup_datetime) as PartitionDate,
cast(null as numeric) as distance_between_service,
cast(null as integer) as time_between_service
from `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2017`
union all
select
'green' as TaxiCompany,
vendor_id as Vendor_Id,
pickup_datetime as Pickup_DateTime,
dropoff_datetime as Dropoff_DateTime,
store_and_fwd_flag as Store_And_Forward,
Rate_Code as Rate_Code_Id,
pickup_location_id as PULocationID,
dropoff_location_id as DOLocationID,
Passenger_Count,
trip_distance as Trip_Distance,
fare_amount as Fare_Amount,
imp_surcharge as Surcharge,
mta_tax as MTA_Tax,
tip_amount as Tip_Amount,
tolls_amount as Tolls_Amount,
cast(null as numeric) as Improvement_Surcharge,
total_amount as Total_Amount,
payment_type as Payment_Type_Id,
cast(null as numeric) as Congestion_Surcharge,
trip_type as Trip_Type, 
cast(Ehail_Fee as numeric) as Ehail_Fee,
date(pickup_datetime) as PartitionDate,
distance_between_service,
time_between_service
from `bigquery-public-data.new_york_taxi_trips.tlc_green_trips_2017`
union all
select
'yellow' as TaxiCompany,
vendor_id as Vendor_Id,
pickup_datetime as Pickup_DateTime,
dropoff_datetime as Dropoff_DateTime,
store_and_fwd_flag as Store_And_Forward,
Rate_Code as Rate_Code_Id,
pickup_location_id as PULocationID,
dropoff_location_id as DOLocationID,
Passenger_Count,
trip_distance as Trip_Distance,
fare_amount as Fare_Amount,
imp_surcharge as Surcharge,
mta_tax as MTA_Tax,
tip_amount as Tip_Amount,
tolls_amount as Tolls_Amount,
cast(null as numeric) as Improvement_Surcharge,
total_amount as Total_Amount,
payment_type as Payment_Type_Id,
cast(null as numeric) as Congestion_Surcharge,
cast(null as string) as Trip_Type,   
cast(null as numeric) as Ehail_Fee,   
date(pickup_datetime) as PartitionDate,
cast(null as numeric) as distance_between_service,
cast(null as integer) as time_between_service
from `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2016`
union all
select
'green' as TaxiCompany,
vendor_id as Vendor_Id,
pickup_datetime as Pickup_DateTime,
dropoff_datetime as Dropoff_DateTime,
store_and_fwd_flag as Store_And_Forward,
Rate_Code as Rate_Code_Id,
pickup_location_id as PULocationID,
dropoff_location_id as DOLocationID,
Passenger_Count,
trip_distance as Trip_Distance,
fare_amount as Fare_Amount,
imp_surcharge as Surcharge,
mta_tax as MTA_Tax,
tip_amount as Tip_Amount,
tolls_amount as Tolls_Amount,
cast(null as numeric) as Improvement_Surcharge,
total_amount as Total_Amount,
payment_type as Payment_Type_Id,
cast(null as numeric) as Congestion_Surcharge,
trip_type as Trip_Type, 
cast(Ehail_Fee as numeric) as Ehail_Fee,
date(pickup_datetime) as PartitionDate,
distance_between_service,
time_between_service
from `bigquery-public-data.new_york_taxi_trips.tlc_green_trips_2016`
union all
select
'yellow' as TaxiCompany,
vendor_id as Vendor_Id,
pickup_datetime as Pickup_DateTime,
dropoff_datetime as Dropoff_DateTime,
store_and_fwd_flag as Store_And_Forward,
Rate_Code as Rate_Code_Id,
pickup_location_id as PULocationID,
dropoff_location_id as DOLocationID,
Passenger_Count,
trip_distance as Trip_Distance,
fare_amount as Fare_Amount,
imp_surcharge as Surcharge,
mta_tax as MTA_Tax,
tip_amount as Tip_Amount,
tolls_amount as Tolls_Amount,
cast(null as numeric) as Improvement_Surcharge,
total_amount as Total_Amount,
payment_type as Payment_Type_Id,
cast(null as numeric) as Congestion_Surcharge,
cast(null as string) as Trip_Type,   
cast(null as numeric) as Ehail_Fee,   
date(pickup_datetime) as PartitionDate,
cast(null as numeric) as distance_between_service,
cast(null as integer) as time_between_service
from `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2015`
union all
select
'green' as TaxiCompany,
vendor_id as Vendor_Id,
pickup_datetime as Pickup_DateTime,
dropoff_datetime as Dropoff_DateTime,
store_and_fwd_flag as Store_And_Forward,
Rate_Code as Rate_Code_Id,
pickup_location_id as PULocationID,
dropoff_location_id as DOLocationID,
Passenger_Count,
trip_distance as Trip_Distance,
fare_amount as Fare_Amount,
imp_surcharge as Surcharge,
mta_tax as MTA_Tax,
tip_amount as Tip_Amount,
tolls_amount as Tolls_Amount,
cast(null as numeric) as Improvement_Surcharge,
total_amount as Total_Amount,
payment_type as Payment_Type_Id,
cast(null as numeric) as Congestion_Surcharge,
trip_type as Trip_Type, 
cast(Ehail_Fee as numeric) as Ehail_Fee,
date(pickup_datetime) as PartitionDate,
distance_between_service,
time_between_service
from `bigquery-public-data.new_york_taxi_trips.tlc_green_trips_2015`
union all
select
'yellow' as TaxiCompany,
vendor_id as Vendor_Id,
pickup_datetime as Pickup_DateTime,
dropoff_datetime as Dropoff_DateTime,
store_and_fwd_flag as Store_And_Forward,
Rate_Code as Rate_Code_Id,
pickup_location_id as PULocationID,
dropoff_location_id as DOLocationID,
Passenger_Count,
trip_distance as Trip_Distance,
fare_amount as Fare_Amount,
imp_surcharge as Surcharge,
mta_tax as MTA_Tax,
tip_amount as Tip_Amount,
tolls_amount as Tolls_Amount,
cast(null as numeric) as Improvement_Surcharge,
total_amount as Total_Amount,
payment_type as Payment_Type_Id,
cast(null as numeric) as Congestion_Surcharge,
cast(null as string) as Trip_Type,   
cast(null as numeric) as Ehail_Fee,   
date(pickup_datetime) as PartitionDate,
cast(null as numeric) as distance_between_service,
cast(null as integer) as time_between_service
from `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2014`
union all
select
'green' as TaxiCompany,
vendor_id as Vendor_Id,
pickup_datetime as Pickup_DateTime,
dropoff_datetime as Dropoff_DateTime,
store_and_fwd_flag as Store_And_Forward,
Rate_Code as Rate_Code_Id,
pickup_location_id as PULocationID,
dropoff_location_id as DOLocationID,
Passenger_Count,
trip_distance as Trip_Distance,
fare_amount as Fare_Amount,
imp_surcharge as Surcharge,
mta_tax as MTA_Tax,
tip_amount as Tip_Amount,
tolls_amount as Tolls_Amount,
cast(null as numeric) as Improvement_Surcharge,
total_amount as Total_Amount,
payment_type as Payment_Type_Id,
cast(null as numeric) as Congestion_Surcharge,
trip_type as Trip_Type, 
cast(Ehail_Fee as numeric) as Ehail_Fee,
date(pickup_datetime) as PartitionDate,
distance_between_service,
time_between_service
from `bigquery-public-data.new_york_taxi_trips.tlc_green_trips_2014`
union all
select
'yellow' as TaxiCompany,
vendor_id as Vendor_Id,
pickup_datetime as Pickup_DateTime,
dropoff_datetime as Dropoff_DateTime,
store_and_fwd_flag as Store_And_Forward,
Rate_Code as Rate_Code_Id,
pickup_location_id as PULocationID,
dropoff_location_id as DOLocationID,
Passenger_Count,
trip_distance as Trip_Distance,
fare_amount as Fare_Amount,
imp_surcharge as Surcharge,
mta_tax as MTA_Tax,
tip_amount as Tip_Amount,
tolls_amount as Tolls_Amount,
cast(null as numeric) as Improvement_Surcharge,
total_amount as Total_Amount,
payment_type as Payment_Type_Id,
cast(null as numeric) as Congestion_Surcharge,
cast(null as string) as Trip_Type,   
cast(null as numeric) as Ehail_Fee,   
date(pickup_datetime) as PartitionDate,
cast(null as numeric) as distance_between_service,
cast(null as integer) as time_between_service
from `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2013`
union all
select
'yellow' as TaxiCompany,
vendor_id as Vendor_Id,
pickup_datetime as Pickup_DateTime,
dropoff_datetime as Dropoff_DateTime,
store_and_fwd_flag as Store_And_Forward,
Rate_Code as Rate_Code_Id,
pickup_location_id as PULocationID,
dropoff_location_id as DOLocationID,
Passenger_Count,
trip_distance as Trip_Distance,
fare_amount as Fare_Amount,
imp_surcharge as Surcharge,
mta_tax as MTA_Tax,
tip_amount as Tip_Amount,
tolls_amount as Tolls_Amount,
cast(null as numeric) as Improvement_Surcharge,
total_amount as Total_Amount,
payment_type as Payment_Type_Id,
cast(null as numeric) as Congestion_Surcharge,
cast(null as string) as Trip_Type,   
cast(null as numeric) as Ehail_Fee,   
date(pickup_datetime) as PartitionDate,
cast(null as numeric) as distance_between_service,
cast(null as integer) as time_between_service
from `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2012`


